THREETUPLE2_SRC_LIB := threetuple2.c
THREETUPLE2_SRC := $(THREETUPLE2_SRC_LIB) threetuple2test.c

THREETUPLE2_SRC_LIB := $(patsubst %,$(DIRTHREETUPLE2)/%,$(THREETUPLE2_SRC_LIB))
THREETUPLE2_SRC := $(patsubst %,$(DIRTHREETUPLE2)/%,$(THREETUPLE2_SRC))

THREETUPLE2_OBJ_LIB := $(patsubst %.c,%.o,$(THREETUPLE2_SRC_LIB))
THREETUPLE2_OBJ := $(patsubst %.c,%.o,$(THREETUPLE2_SRC))

THREETUPLE2_DEP_LIB := $(patsubst %.c,%.d,$(THREETUPLE2_SRC_LIB))
THREETUPLE2_DEP := $(patsubst %.c,%.d,$(THREETUPLE2_SRC))

CFLAGS_THREETUPLE2 := -I$(DIRHASHLIST) -I$(DIRMISC) -I$(DIRHASHTABLE) -I$(DIRTIMERLINKHEAP) -I$(DIRAIRWALL) -I$(DIRLINKEDLIST)
LIBS_THREETUPLE2 := $(DIRMISC)/libmisc.a $(DIRHASHTABLE)/libhashtable.a $(DIRLOG)/liblog.a $(DIRTIMERLINKHEAP)/libtimerlinkheap.a $(DIRAIRWALL)/libairwall.a

MAKEFILES_THREETUPLE2 := $(DIRTHREETUPLE2)/module.mk

.PHONY: THREETUPLE2 clean_THREETUPLE2 distclean_THREETUPLE2 unit_THREETUPLE2 $(LCTHREETUPLE2) clean_$(LCTHREETUPLE2) distclean_$(LCTHREETUPLE2) unit_$(LCTHREETUPLE2)

$(LCTHREETUPLE2): THREETUPLE2
clean_$(LCTHREETUPLE2): clean_THREETUPLE2
distclean_$(LCTHREETUPLE2): distclean_THREETUPLE2
unit_$(LCTHREETUPLE2): unit_THREETUPLE2

THREETUPLE2: $(DIRTHREETUPLE2)/libthreetuple2.a $(DIRTHREETUPLE2)/threetuple2test

unit_THREETUPLE2:
	@true

$(DIRTHREETUPLE2)/libthreetuple2.a: $(THREETUPLE2_OBJ_LIB) $(MAKEFILES_COMMON) $(MAKEFILES_THREETUPLE2)
	rm -f $@
	ar rvs $@ $(filter %.o,$^)

$(DIRTHREETUPLE2)/threetuple2test: $(DIRTHREETUPLE2)/threetuple2test.o $(DIRTHREETUPLE2)/libthreetuple2.a $(LIBS_THREETUPLE2) $(MAKEFILES_COMMON) $(MAKEFILES_THREETUPLE2)
	$(CC) $(CFLAGS) -o $@ $(filter %.o,$^) $(filter %.a,$^) $(CFLAGS_THREETUPLE2)

$(THREETUPLE2_OBJ): %.o: %.c %.d $(MAKEFILES_COMMON) $(MAKEFILES_THREETUPLE2)
	$(CC) $(CFLAGS) -c -o $*.o $*.c $(CFLAGS_THREETUPLE2)
	$(CC) $(CFLAGS) -c -S -o $*.s $*.c $(CFLAGS_THREETUPLE2)

$(THREETUPLE2_DEP): %.d: %.c $(MAKEFILES_COMMON) $(MAKEFILES_THREETUPLE2)
	$(CC) $(CFLAGS) -MM -MP -MT "$*.d $*.o" -o $*.d $*.c $(CFLAGS_THREETUPLE2)

clean_THREETUPLE2:
	rm -f $(THREETUPLE2_OBJ) $(THREETUPLE2_DEP)

distclean_THREETUPLE2: clean_THREETUPLE2
	rm -f $(DIRTHREETUPLE2)/libthreetuple2.a $(DIRTHREETUPLE2)/threetuple2test

-include $(DIRTHREETUPLE2)/*.d
